swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:5000
basePath: /
schemes:
  - http
paths:
  /:
    get:
      summary: Returns Greeting.
      responses:
        200:
          description: OK